// Posts
export const POST = "POST";
export const LIST_ALL = "LIST_ALL";

// Authentication
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGOUT = "LOGOUT";

// Interactions
export const UPVOTE_POST_SUCCESS = "UPVOTE_POST_SUCCESS";
export const UPVOTE_POST_FAILURE = "UPVOTE_POST_FAILURE";
export const DOWNVOTE_POST_SUCCESS = "DOWNVOTE_POST_SUCCESS";
export const DOWNVOTE_POST_FAILURE = "DOWNVOTE_POST_FAILURE";
export const GET_VOTE_SUM_TOTAL = "GET_VOTE_SUM_TOTAL_SUCCESS";
export const GET_VOTE_SUM_TOTAL_FAILURE = "GET_VOTE_SUM_TOTAL_FAILURE";

// Users
export const GET_ALL_USERS = "GET_ALL_USERS";
