# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM Dependencies
        run: npm ci
      - name: Build React App
        run: npm run build
      # - run: npm test

      - name: Deploy to server via SSH
        # You may pin to the exact commit or the version.
        # uses: easingthemes/ssh-deploy@9ab39935552e9fe6706e9c9bf2a70a3328a4a5e6
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          ARGS: "-rltgoDzvO"
          SOURCE: "build/"
          TARGET: ${{ secrets.REMOTE_TARGET }}
      # - name: Deploy to server via SSH
      #   run: |
      #     cd ~/ && mkdir -p ~/.ssh/known_hosts &&
      #     echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./private.key
      #     sudo chmod 600 ./private.key
      #     rsync -aPvz build tony@143.198.230.98:~/
      #     ssh tony@143.198.320.98
